blank_issues_enabled: false

issue_templates:
  - name: Bug
    description: Report a bug in RetroSpectacle
    labels: [bug]
    body: |
      ## Description
      <!-- Describe the bug clearly -->

      ## Steps to Reproduce
      1. 
      2. 
      3. 

      ## Expected Behavior

      ## Actual Behavior

      ## Screenshots / Notes

  - name: Feature
    description: Suggest a new feature or enhancement
    labels: [enhancement]
    body: |
      ## Feature Description

      ## User Story / Goal

      ## Acceptance Criteria
      - [ ] 
      - [ ] 

      ## Mockups / References

  - name: Task
    description: General task or chore for RetroSpectacle
    labels: [todo]
    body: |
      ## Type of Task
      - [ ] Frontend
      - [ ] Backend
      - [ ] Database
      - [ ] Integration
      - [ ] Documentation
      - [ ] Other

      ## Priority
      - [ ] High
      - [ ] Medium
      - [ ] Low

      ## Description

      ## Steps / Requirements
      1. 
      2. 
      3. 

      ## Notes / References
