name: Add PR Link to Issue

on:
  pull_request:
    types: [opened, reopened]

jobs:
  link-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue is referenced
        id: check-issue
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          # Look for issue references like #123
          if [[ $PR_BODY =~ \#([0-9]+) ]]; then
            ISSUE_NUMBER="${BASH_REMATCH[1]}"
            echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV
            echo "PR_URL=$PR_URL" >> $GITHUB_ENV
            echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          else
            echo "No issue referenced in PR description"
            exit 0
          fi

      - name: Add comment to linked issue
        if: env.ISSUE_NUMBER
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = process.env.ISSUE_NUMBER;
            const prUrl = process.env.PR_URL;
            const prTitle = process.env.PR_TITLE;

            // Add a comment to the issue
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `🔗 **Linked Pull Request**: [${prTitle}](${prUrl})\n\nThis pull request references this issue.`
            });

            console.log(`Added PR link to issue #${issueNumber}`);
